update version

diff --git a/.github/workflows/go-bulk-release-core-libs.yaml b/.github/workflows/go-bulk-release-core-libs.yaml
--- a/.github/workflows/go-bulk-release-core-libs.yaml
+++ b/.github/workflows/go-bulk-release-core-libs.yaml
@@ -1,6 +1,6 @@
 # $schema: https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
 
-name: "Go bulk release of core libs"
+name: "Go bulk release core libs"
 run-name: Go bulk release of core-libs [${{ inputs.repositoryToRelease }}] by @${{ github.actor }}'
 
 on:
@@ -31,14 +31,6 @@ on:
           - qubership-core-lib-go-paas-mediation-client
           - qubership-core-lib-go-rest-utils
           - qubership-core-lib-go-stomp-websocket
-      versionIncrementType:
-        description: "Version part to increment"
-        type: choice
-        options:
-          - patch
-          - minor
-          - major
-        default: patch
       skipTest:
         description: "skip tests"
         type: boolean
@@ -72,52 +64,51 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: "main"
-          # todo vlla: зачем выкачивать этот репозиторий?
 
-#      - name: "Download GAVs from another release workflow(s)"
-#        id: download-gavs
-#        if: ${{ inputs.runIdsWithGAVs != '' || inputs.gavs != '' }}
-#        shell: bash
-#        env:
-#          RUN_IDS: ${{ inputs.runIdsWithGAVs }}
-#          INPUT_GAVS: ${{ inputs.gavs }}
-#        # language="shell script"
-#        run: |-
-#          GAVS="${INPUT_GAVS}"
-#          IFS=','
-#          for runId in ${RUN_IDS}; do
-#            url="https://api.github.com/repos/Netcracker/qubership-core-infra/actions/runs/${runId}/artifacts"
-#            gavsFile="gavs.txt"
-#            zipUrl=$(curl -s -L -H "Authorization: Bearer ${MAVEN_TOKEN}" "${url}" | jq -r --arg name "${gavsFile}" '.artifacts[] | select(.name == $name) | .archive_download_url')
-#            if [ -s "${zipUrl}" ]; then
-#              echo "artifacts from ${url} do not contain ${gavsFile} artifact"
-#              exit 1
-#            fi
-#            dir="/tmp/gavs_artifacts/${runId}"
-#
-#            mkdir -p "${dir}"
-#
-#            zipFile="${dir}/gavs.zip"
-#            echo "Downloading ${gavsFile} from ${zipUrl}"
-#            curl -o "${zipFile}" -L -H "Authorization: Bearer ${MAVEN_TOKEN}" "${zipUrl}" || { echo "Failed to download ${gavsFile}"; exit 1; }
-#
-#            echo "Extracting ${zipFile} to ${dir}"
-#            unzip -o "${zipFile}" -d "${dir}" || { echo "Failed to extract ${zipFile}"; exit 1; }
-#
-#            extractedGAVsFile="${dir}/${gavsFile}"
-#            if [ -e "${extractedGAVsFile}" ]; then
-#              gavs=$(cat "${extractedGAVsFile}" | tr '\n' ',')
-#              if [ -n "${GAVS}" ]; then
-#                 GAVS="${GAVS},${gavs}"
-#              else
-#                 GAVS="${gavs}"
-#              fi
-#            else
-#              echo "File ${extractedGAVsFile} not found"
-#              exit 1
-#            fi
-#          done
-#          echo "gavs=${GAVS}" >> "${GITHUB_OUTPUT}"
+      #      - name: "Download GAVs from another release workflow(s)"
+      #        id: download-gavs
+      #        if: ${{ inputs.runIdsWithGAVs != '' || inputs.gavs != '' }}
+      #        shell: bash
+      #        env:
+      #          RUN_IDS: ${{ inputs.runIdsWithGAVs }}
+      #          INPUT_GAVS: ${{ inputs.gavs }}
+      #        # language="shell script"
+      #        run: |-
+      #          GAVS="${INPUT_GAVS}"
+      #          IFS=','
+      #          for runId in ${RUN_IDS}; do
+      #            url="https://api.github.com/repos/Netcracker/qubership-core-infra/actions/runs/${runId}/artifacts"
+      #            gavsFile="gavs.txt"
+      #            zipUrl=$(curl -s -L -H "Authorization: Bearer ${MAVEN_TOKEN}" "${url}" | jq -r --arg name "${gavsFile}" '.artifacts[] | select(.name == $name) | .archive_download_url')
+      #            if [ -s "${zipUrl}" ]; then
+      #              echo "artifacts from ${url} do not contain ${gavsFile} artifact"
+      #              exit 1
+      #            fi
+      #            dir="/tmp/gavs_artifacts/${runId}"
+      #
+      #            mkdir -p "${dir}"
+      #
+      #            zipFile="${dir}/gavs.zip"
+      #            echo "Downloading ${gavsFile} from ${zipUrl}"
+      #            curl -o "${zipFile}" -L -H "Authorization: Bearer ${MAVEN_TOKEN}" "${zipUrl}" || { echo "Failed to download ${gavsFile}"; exit 1; }
+      #
+      #            echo "Extracting ${zipFile} to ${dir}"
+      #            unzip -o "${zipFile}" -d "${dir}" || { echo "Failed to extract ${zipFile}"; exit 1; }
+      #
+      #            extractedGAVsFile="${dir}/${gavsFile}"
+      #            if [ -e "${extractedGAVsFile}" ]; then
+      #              gavs=$(cat "${extractedGAVsFile}" | tr '\n' ',')
+      #              if [ -n "${GAVS}" ]; then
+      #                 GAVS="${GAVS},${gavs}"
+      #              else
+      #                 GAVS="${gavs}"
+      #              fi
+      #            else
+      #              echo "File ${extractedGAVsFile} not found"
+      #              exit 1
+      #            fi
+      #          done
+      #          echo "gavs=${GAVS}" >> "${GITHUB_OUTPUT}"
 
       - name: "Read repositories"
         id: read-repositories
@@ -161,26 +152,27 @@ jobs:
           gpg-private-key: ${{ inputs.maven-gpg-private-key }}
           gpg-passphrase: MAVEN_GPG_PASSPHRASE
 
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: '1.24.2'
+
+      - name: "Install gomajor"
+        run: |
+          go install github.com/taurmorchant/gomajor@v0.15.2
+          gomajor -h
+
       - name: "Download go-pack tool"
         run: |
-          VER="v1.0.0" 
-          BASE="https://github.com/TaurMorchant/go-pack/releases/download/${VER}"
-          curl -fL "$BASE/gopack" -o gopack
-          curl -fL "$BASE/SHA256SUMS" -o SHA256SUMS
-          
-          sha256sum -c --ignore-missing SHA256SUMS
-          
-          chmod +x gopack
-          echo "$(pwd)" >> $GITHUB_PATH
+          go install github.com/taurmorchant/go-pack@v1.1.4
+          which go-pack
 
-      - name: "Install GoReleaser"
-        env:
-          GORELEASER_VERSION: "2.11.2"
+      - name: Install go-semantic-release
         run: |
-          curl -fsSL -o goreleaser.deb \
-            "https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_${GORELEASER_VERSION}_amd64.deb"
-          sudo dpkg -i goreleaser.deb
-          goreleaser -v
+          curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ./semantic-release
+          chmod +x ./semantic-release
+          sudo mv semantic-release /usr/local/bin/semantic-release
+          semantic-release --version
 
       - name: "Run go-bulk-release-cli"
         id: run-go-bulk-release-cli
@@ -189,17 +181,15 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.MAVEN_RELEASE_DEV_TOKEN }}
           REPOSITORIES: ${{ steps.read-repositories.outputs.repositories }}
           REPOSITORY_TO_RELEASE: ${{ inputs.repositoryToRelease }}
-          VERSION_INCREMENT_TYPE: ${{ inputs.versionIncrementType }}
           SKIP_TEST: ${{ inputs.skipTest }}
           DRY_RUN: ${{ inputs.dryRun }}
         # language="shell script"
         run: |
           mkdir /tmp/GOPROXY
-          cp ./.github/goreleaser.yaml /tmp/
           
           # todo vlla почему maven-bulk-release-cli выкачивается из репозитория qubership-core-infra?
           cliVersion="1.2.4-SNAPSHOT"
-          snapshotVersion="1.3.0-20250820.060047-34"
+          snapshotVersion="1.3.0-20250826.114757-62"
           
           url="https://maven.pkg.github.com/netcracker/qubership-core-bulk-release/org/qubership/cloud/go-bulk-release-cli/1.3.0-SNAPSHOT/go-bulk-release-cli-${snapshotVersion}-jar-with-dependencies.jar"
           curl --fail -L -o "go-bulk-release-cli.jar" -H "Authorization: Bearer ${MAVEN_TOKEN}" "${url}"
@@ -225,7 +215,6 @@ jobs:
           args="${args} --gitPassword=${MAVEN_TOKEN}"
           args="${args} --repositories=${REPOSITORIES}"
           args="${args} --repositoriesToReleaseFrom=${repositoryToRelease}"
-          args="${args} --versionIncrementType=${VERSION_INCREMENT_TYPE}"
           args="${args} --resultOutputFile=${GITHUB_OUTPUT}"
           args="${args} --summaryFile=${GITHUB_STEP_SUMMARY}"
           args="${args} --gavsResultFile=/tmp/gavs.txt"
